### ISSUE TITLE
Tags Not working

### ISSUE THREAD

**Issue by FranciscodeMaussion** [passy/financius2bluecoins#3]
`financius2bluecoin: SQLite3 returned ErrorError while attempting to perform prepare "INSERT INTO TRANSACTIONSTABLE (itemID, amount, notes, accountID, transactionCurrency, conversionRateNew, transactionTypeID, categoryID, tags, accountReference, accountPairID, uidPairID, deletedTransaction, hasPhoto, labelCount, date) VALUES (:itemID, :amount, :notes, :accountID, :transactionCurrency, :conversionRateNew, :transactionTypeID, :categoryID, :tags, :accountReference, :accountPairID, :uidPairID, :deletedTransaction, :hasPhoto, :labelCount, :date)": table TRANSACTIONSTABLE has no column named tags
`
Corrected deleting tags from .hs

**Comment by passy** [comment]
Hm, I wouldn't be surprised if the schema on the Bluecoins side has changed and my script only works for one particular snapshot in time.

Did it work for you after removing the tags?

**Comment by FranciscodeMaussion** [comment]
After removing them, it works correctly. The other issue I found is with
the deleted categories in the financius json, but idk if it was because the
tags issue.
Finally the reason why EUR is not working it because is the base currency
for the cvs download, you may add a column with all values in 1 if you want
this to work.
